include: package:flutter_lints/flutter.yaml

linter:
  rules:
  # Add your custom rules here if needed

analyzer:
  errors:
    # Enable strong mode analysis options
    strong-mode:
      implicit-casts: false
      implicit-dynamic: false
      non-nullable: true
